### ISSUE TITLE
Run miri as part of the CI

### ISSUE THREAD

**Issue by vks** [google/moveit#15]
It might be worthwhile to run the tests with miri to check for undefined behavior. Adding the following job (adapted from Rand) to the GitHub actions should work:

```yaml
  test-miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        run: |
          MIRI_NIGHTLY=nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri)
          rustup default "$MIRI_NIGHTLY"
          rustup component add miri
      - name: Test rand
        run: |
          cargo miri test
```
